# Generated by Django 3.0 on 2020-04-12 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=25, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('customer_city', models.CharField(max_length=25, null=True)),
                ('customer_zip', models.IntegerField(null=True)),
                ('customer_state', models.CharField(max_length=25, null=True)),
                ('customer_email', models.CharField(max_length=25, null=True)),
                ('customer_phone', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='product',
            name='book_author',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book_isbn',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book_publisher',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='book_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='date_received',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=255, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product')),
            ],
        ),
    ]
