# Generated by Django 3.0 on 2020-04-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200412_0754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_zip',
            new_name='zip',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='book_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='book_isbn',
            new_name='isbn',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='book_publisher',
            new_name='publisher',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='book_quantity',
            new_name='quantity',
        ),
    ]
