# Generated by Django 3.0 on 2020-04-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200412_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='note',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='note',
            field=models.CharField(max_length=255),
        ),
    ]
