# Generated by Django 3.0 on 2020-04-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200412_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='note',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='note',
        ),
    ]
