# Generated by Django 3.0 on 2020-04-12 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200412_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_out', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Checked In', 'Checked In'), ('Checked Out', 'Checked Out')], max_length=255, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Product')),
            ],
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='product',
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='CheckOut',
        ),
    ]
