# Generated by Django 3.0 on 2020-04-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200413_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('CA', 'CA'), ('OR', 'OR')], max_length=2, null=True),
        ),
    ]
