# Generated by Django 3.0 on 2020-04-14 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20200413_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quantities', to='accounts.Product'),
        ),
    ]
