# Generated by Django 3.0 on 2020-05-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20200419_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueorder',
            name='status',
            field=models.CharField(choices=[('Checked Out', 'Checked Out')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='returnorder',
            name='status',
            field=models.CharField(choices=[('Checked In', 'Checked In')], max_length=255, null=True),
        ),
    ]
